source("utilities.R")

#Import csv/xlsx file, auto-convert N/A as NA, preserve original column names
rawdata <- readData("combineddata.xlsx", na.strings = c("NA", "BLANK", "MULT", "ERROR #3100", "#VALUE!", "Not Asked"), check.names = FALSE)

#Remove empty rows
rawdata <- rawdata[rowSums(is.na(rawdata) | rawdata == "") != ncol(rawdata),]

# ---Check for "out-of-range" records---
#Import rangeOfValues.csv, which specifies possible answers for each question, to formatDF dataframe
formatDF <- read.csv("rangeOfValues.csv", header = TRUE, sep = ",", na.strings = c("--"), check.names = FALSE, stringsAsFactors = FALSE) 

#Check data column-by-column, first, column names are generated by colnames(formatDF)
#For each column name, sapply will call checkdata function, to check the corresponding column in rawdata
#The return value of checkdata() is a dataframe and sapply() will convert those dataframes in each call into a list
invalidDF <- sapply(colnames(formatDF), function(x) checkdata(rawdata, formatDF[[x]], x))

#Merge dataframe fragments in the list into a single dataframe
invalidDF <- as.data.frame(do.call(rbind, invalidDF))

#Remove unnecessary rownames
rownames(invalidDF) <- NULL


# ---Summarize---
print(paste("No. of records: ", nrow(rawdata), sep = ""))
if (length(invalidDF) != 0){
  print(paste("No. of invalid cells: ", nrow(invalidDF), sep = ""))
  write.csv(invalidDF, file = "invalidData.csv", row.names = FALSE)
} else{
  rm(invalidDF)
  print(paste("There is no invalid cell", sep = ""))
}

#Convert columns to numeric, unless it contains character value
rawdata <- lapply(rawdata, function(x) chartoNumeric(x))
rawdata <- as.data.frame(rawdata, check.names = FALSE, stringsAsFactors = FALSE)